version: 2.1

executors:
  carbon:
    working_directory: ~/jsx-slack
    docker:
      - image: circleci/node:carbon

  dubnium:
    working_directory: ~/jsx-slack
    docker:
      - image: circleci/node:dubnium

  erbium:
    working_directory: ~/jsx-slack
    docker:
      - image: circleci/node:12

commands:
  test:
    steps:
      - checkout
      - run: node --version

      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
            - dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-
            - dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-

      - run: yarn install
      - run: yarn audit

      - save_cache:
          key: dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
          paths:
            - node_modules
            - ~/.cache/yarn

      - run:
          name: Prettier formatting
          command: yarn check:format

      - run:
          name: TypeScript type checking
          command: yarn check:ts

      - run:
          name: ESLint
          command: yarn lint

      - run:
          name: Jest
          command: yarn test:coverage --ci --maxWorkers=2 --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: tmp/test-results/jest.xml

      - store_test_results:
          path: tmp/test-results

      - store_artifacts:
          path: ./coverage
          destination: coverage

      - run: yarn codecov

jobs:
  carbon:
    executor:
      name: carbon
    steps:
      - test

  dubnium:
    executor:
      name: dubnium
    steps:
      - test

  erbium:
    executor:
      name: erbium
    steps:
      - test

workflows:
  build:
    jobs:
      - carbon
      - dubnium
      - erbium
